//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowledgeManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssociatedTag
    {
        public int AId { get; set; }
        public int TagId { get; set; }
        public int AssociatedId { get; set; }
    
        public virtual Tag Tag { get; set; }
        public virtual Tag Tag1 { get; set; }
    }
}
